//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.NET.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cleaner.NET.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_TabItem {
            get {
                return ResourceManager.GetString("About_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string Analyze_Button {
            get {
                return ResourceManager.GetString("Analyze_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate size of files to be deleted:.
        /// </summary>
        public static string AnalyzeLog {
            get {
                return ResourceManager.GetString("AnalyzeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected plugin, which can not be loaded. Please remove it from the plugins folder. Path:.
        /// </summary>
        public static string BadPlugin {
            get {
                return ResourceManager.GetString("BadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache MUI.
        /// </summary>
        public static string CacheMUI {
            get {
                return ResourceManager.GetString("CacheMUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose elements:.
        /// </summary>
        public static string ChooseElements {
            get {
                return ResourceManager.GetString("ChooseElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string Clean_Button {
            get {
                return ResourceManager.GetString("Clean_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaner.
        /// </summary>
        public static string Cleaner_TabItem {
            get {
                return ResourceManager.GetString("Cleaner_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed file size:.
        /// </summary>
        public static string CleanLog {
            get {
                return ResourceManager.GetString("CleanLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Clipboard_CheckBox {
            get {
                return ResourceManager.GetString("Clipboard_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty.
        /// </summary>
        public static string ClipboardClean {
            get {
                return ResourceManager.GetString("ClipboardClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard will be empty.
        /// </summary>
        public static string ClipboardNotClean {
            get {
                return ResourceManager.GetString("ClipboardNotClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache DNS will be deleted .
        /// </summary>
        public static string FlushDns {
            get {
                return ResourceManager.GetString("FlushDns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning cache DNS failed!.
        /// </summary>
        public static string FlushDns_Error {
            get {
                return ResourceManager.GetString("FlushDns_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully flushed the DNS Resolver Cache.
        /// </summary>
        public static string FlushDns_OK {
            get {
                return ResourceManager.GetString("FlushDns_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing reference to the DLL.
        /// </summary>
        public static string MissingDLL {
            get {
                return ResourceManager.GetString("MissingDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing files.
        /// </summary>
        public static string MissingFiles {
            get {
                return ResourceManager.GetString("MissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing MUI reference.
        /// </summary>
        public static string MissingMUI {
            get {
                return ResourceManager.GetString("MissingMUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgWarning {
            get {
                return ResourceManager.GetString("MsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-existent Software.
        /// </summary>
        public static string NonExistentSoftware {
            get {
                return ResourceManager.GetString("NonExistentSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other_TabItem {
            get {
                return ResourceManager.GetString("Other_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected plugin is not designed to work with this program version! Do you want to load it in spite of this? Path:.
        /// </summary>
        public static string OutOfDatePlugin {
            get {
                return ResourceManager.GetString("OutOfDatePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred plugin, details:.
        /// </summary>
        public static string PluginError {
            get {
                return ResourceManager.GetString("PluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugins:.
        /// </summary>
        public static string PluginsLoaded {
            get {
                return ResourceManager.GetString("PluginsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent documents.
        /// </summary>
        public static string Recentdoc_CheckBox {
            get {
                return ResourceManager.GetString("Recentdoc_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty trash.
        /// </summary>
        public static string RecycleBin_CheckBox {
            get {
                return ResourceManager.GetString("RecycleBin_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string Registry_TabItem {
            get {
                return ResourceManager.GetString("Registry_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected entries.
        /// </summary>
        public static string RegistryClean {
            get {
                return ResourceManager.GetString("RegistryClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search unnecessary entries.
        /// </summary>
        public static string RegistrySearch {
            get {
                return ResourceManager.GetString("RegistrySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_TabItem {
            get {
                return ResourceManager.GetString("Settings_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System information.
        /// </summary>
        public static string SystemInformation_TabItem {
            get {
                return ResourceManager.GetString("SystemInformation_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary files.
        /// </summary>
        public static string Temp_CheckBox {
            get {
                return ResourceManager.GetString("Temp_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache DNS.
        /// </summary>
        public static string TempDns_CheckBox {
            get {
                return ResourceManager.GetString("TempDns_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font cache.
        /// </summary>
        public static string TempFont_CheckBox {
            get {
                return ResourceManager.GetString("TempFont_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails cache.
        /// </summary>
        public static string ThumbnailsCache_CheckBox {
            get {
                return ResourceManager.GetString("ThumbnailsCache_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash is empty.
        /// </summary>
        public static string TrashClean {
            get {
                return ResourceManager.GetString("TrashClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash will be empty.
        /// </summary>
        public static string TrashNoClean {
            get {
                return ResourceManager.GetString("TrashNoClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a beta version of the application, so it may contain errors!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows_TabItem {
            get {
                return ResourceManager.GetString("Windows_TabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Error Reporting.
        /// </summary>
        public static string WinErrors_CheckBox {
            get {
                return ResourceManager.GetString("WinErrors_CheckBox", resourceCulture);
            }
        }
    }
}
